version: '3.8'

services:
  # 온톨로지(지식 그래프) DB
  ontology-db:
    image: neo4j:latest
    container_name: ontology_neo4j
    ports:
      - "7474:7474" # HTTP 브라우저 접속 (http://localhost:7474)
      - "7687:7687" # Bolt 포트 (앱 연결용)
    environment:
      - NEO4J_AUTH=neo4j/!@ssw5740  # ID: mrg / PW: !@ssw5740 (변경 가능)
    volumes:
      - ./neo4j_data:/data